import { ref } from 'vue'

export const learningCategories = ref([
    {
        category: 'Pelajaran Dasar',
        icon: '📚',
        colorClass: 'from-blue-500 to-blue-600',
        items: Array.from({ length: 16 }, (_, i) => `Belajar Bahasa Inggris Ke ${i + 1}`),
    },
    {
        category: 'Kosakata Umum',
        icon: '⚡',
        colorClass: 'from-amber-500 to-orange-600',
        count: 233,
        description: 'Kosakata Bahasa Inggris Umum',
        bgGradient: 'from-amber-500 to-orange-600',
    },
    {
        category: 'Kata Kerja',
        icon: '🎯',
        colorClass: 'from-emerald-500 to-teal-600',
        count: 137,
        description: 'Kosakata Bahasa Inggris Kata Kerja',
        bgGradient: 'from-emerald-500 to-teal-600',
    },
    {
        category: 'Kata Sifat',
        icon: '✨',
        colorClass: 'from-rose-500 to-pink-600',
        count: 111,
        description: 'Kosakata Bahasa Inggris Kata Sifat',
        bgGradient: 'from-rose-500 to-pink-600',
    },
])

// Data Lesson Content (Array of Array)
export const lessonContent = ref([
    // --- Hari Ke 1 (Index 0) ---
    [
        { kalimat: 'Take It Easy', arti: 'Santai aja' },
        { kalimat: 'Let Me Be', arti: 'Biarkan aku saja' },
        { kalimat: 'For What', arti: 'Untuk apa' },
        { kalimat: 'Dead Meat', arti: 'Matilah kau' },
        { kalimat: 'What\'s Up ?', arti: 'Hai Apa Kabar ?' },
        { kalimat: 'Nothing Much', arti: 'Biasa saja' },
        { kalimat: 'I guess so', arti: 'Saya pikir juga begitu' },
        { kalimat: 'Don\'t bother', arti: 'Jangan ganggu' },
        { kalimat: 'No hard feeling', arti: 'Jangan tersinggung' },
        { kalimat: 'Don\'t be Noisy', arti: 'Jangan rame' },
        { kalimat: 'Piece of cake', arti: 'Mudah sekali' },
        { kalimat: 'Poor thing', arti: 'Kasihannya' },
        { kalimat: 'So what ?', arti: 'Lalu kenapa ?' },
        { kalimat: 'So so', arti: 'Biasa saja' },
        { kalimat: 'Just for fun', arti: 'Hanya tuk senang-senang' },
        { kalimat: 'One way or another', arti: 'ini atau itu' },
        { kalimat: 'Help yourself !', arti: 'Bantu diri anda sendiri' },
        { kalimat: 'Absolutely !', arti: 'Tentu Saja' },
        { kalimat: 'What have you been doing', arti: 'Apa yang telah Anda lakukan' },
        { kalimat: 'Nothing Much', arti: 'Bukan apa apa' },
    ],

    // --- Hari Ke 2 (Index 1) ---
    [
        { kalimat: 'What\'s on your mind ?', arti: 'Apa yang anda pikirkan ?' },
        { kalimat: 'I was just thinking', arti: 'Saya hanya sedang berpikir' },
        { kalimat: 'I was just day dreaming', arti: 'Saya hanya sedang melamun' },
        { kalimat: 'It\'s none of your business', arti: 'Bukan urusan Anda' },
        { kalimat: 'Is that so ?', arti: 'Hanya itu ?' },
        { kalimat: 'How come ?', arti: 'Bagaimana bisa ?' },
        { kalimat: 'How\'s it going ?', arti: 'Bagaimana itu berjalan ?' },
        { kalimat: 'Definitely !', arti: 'Tentu saja !' },
        { kalimat: 'Of course !', arti: 'Pastinya !' },
        { kalimat: 'You better believe it !', arti: 'Anda harus mempercayainya' },
        { kalimat: 'I guess so', arti: 'Saya pikir begitu' },
        { kalimat: 'There\'s no way to know', arti: 'Tidak ada cara untuk mengetahuinya' },
        { kalimat: 'I can\'t say for sure', arti: 'Saya tidak dapat memastikannya' },
        { kalimat: 'This is too good to be true', arti: 'Terlalu baik untuk menjadi kenyataan' },
        { kalimat: 'No way, stop joking !', arti: 'Sudah ! Cukup bercandanya' },
        { kalimat: 'I got it', arti: 'Saya paham' },
        { kalimat: 'Right on! (Great)', arti: 'Luar biasa' },
        { kalimat: 'I did it! ( I made it )', arti: 'Saya berhasil melakukannya' },
        { kalimat: 'Got a minute ?', arti: 'Anda punya waktu sebentar ?' },
        { kalimat: 'About when ?', arti: 'Sekitar kapan ?' },
    ],

    // --- Hari Ke 3 (Index 2) ---
    [
        { kalimat: "I won't take but a minute", arti: 'Saya tidak akan lama, hanya sebentar' },
        { kalimat: 'Speak up !', arti: 'Bicaralah !' },
        { kalimat: 'Never mind', arti: 'Tidak masalah' },
        { kalimat: "So we've met again, Eh?", arti: 'Jadi kita bertemu lagi khan ?' },
        { kalimat: 'Come here', arti: 'Kemarilah' },
        { kalimat: 'Come over', arti: 'Datanglah' },
        { kalimat: "Don't go yet", arti: 'Jangan pergi dulu' },
        { kalimat: 'Please go first. After you', arti: 'Pergilah dahulu, saya menyusul' },
        { kalimat: 'Thanks for letting me go first', arti: 'Terima kasih telah mengizinkan saya pergi dahulu' },
        { kalimat: 'What a relief', arti: 'Sangat melegakan' },
        { kalimat: 'Bad luck !', arti: 'Sial !' },
        { kalimat: "You're a life saver", arti: 'Anda adalah penyelamat hidup' },
        { kalimat: 'I know I can count on you', arti: 'Saya tahu saya bisa mengandalkan Anda' },
        { kalimat: 'Anything else ?', arti: 'Ada lagi ?' },
        { kalimat: 'Do as I say', arti: 'Lakukan seperti apa yang saya katakan' },
        { kalimat: 'This is the limit !', arti: 'Ini adalah batasnya' },
        { kalimat: 'Explain to me why', arti: 'Jelaskan pada saya kenapa' },
        { kalimat: 'Ask for it!', arti: 'Tanyalah!' },
        { kalimat: 'In the nick of time', arti: 'Hampir terlambat' },
        { kalimat: 'No litter', arti: 'Dilarang buang sampah sembarangan' },
    ],

    // --- Hari Ke 4 (Index 3) ---
    [
        { kalimat: 'Go for it!', arti: 'Lanjutkan!' },
        { kalimat: "Don't forget", arti: 'Jangan lupa' },
        { kalimat: 'How cute!', arti: 'Lucunya!' },
        { kalimat: 'None of your business!', arti: 'Bukan urusan Anda!' },
        { kalimat: "Don't peep!", arti: 'Jangan mengintip!' },
        { kalimat: "What i'm going to do if...", arti: 'Apa yang akan saya lakukan jika ...' },
        { kalimat: 'Stop it right away!', arti: 'Berhenti sekarang' },
        { kalimat: 'A wise guy, eh?!', arti: 'Laki-laki bijaksana bukan ?!' },
        { kalimat: 'Be good !', arti: 'Jadilah anak baik' },
        { kalimat: "You'd better stop dawdling", arti: 'Berhenti membuang waktu' },
        { kalimat: 'Say cheese!', arti: 'Katakan kejuu!' },
        { kalimat: 'Please speak more slowly!', arti: 'Tolong bicara lebih pelan' },
        { kalimat: 'Me? Not likely', arti: 'Saya ? Tidak seperti itu' },
        { kalimat: "Scratch one's head", arti: 'Berpikir keras' },
        { kalimat: 'Take it or leave it !', arti: 'Ambil atau tinggalkan' },
        { kalimat: 'What a pity', arti: 'Sayangnya' },
        { kalimat: 'Congratulations !', arti: 'Selamat !' },
        { kalimat: 'Mark my words', arti: 'Ingat kata-kata saya' },
        { kalimat: 'Boys will be boys', arti: 'Anak lak-laki akan selalu jadi anak laki-laki' },
        { kalimat: 'Good job! Well done!', arti: 'Bagus sekali' },
    ],


    // --- Hari Ke 5 (Index 4) ---
    [
        { kalimat: 'Just for fun', arti: 'Hanya untuk senang-senang' },
        { kalimat: 'Try your best !', arti: 'Cobalah yang terbaik' },
        { kalimat: 'Make some noise!', arti: 'Membuat kegaduhan' },
        { kalimat: 'Calm down!', arti: 'Tenanglah' },
        { kalimat: 'Go for it!', arti: 'Lanjutkanlah!' },
        { kalimat: 'Strike it lucky', arti: 'Membuat keberuntungan' },
        { kalimat: 'Always the same', arti: 'Selalu begitu/sama saja' },
        { kalimat: 'Hit it off', arti: 'Supel' },
        { kalimat: 'Hit or miss', arti: 'Sekarang atau kehilangan kesempatan' },
        { kalimat: 'Add fuel to the fire', arti: 'Semakin membuat parah keadaan' },
        { kalimat: "Don't mention it / Not at all", arti: 'Bukan apa apa' },
        { kalimat: 'Just Kidding', arti: 'Hanya bercanda' },
        { kalimat: 'No, not a bit', arti: 'Tidak sedikitpun' },
        { kalimat: 'Nothing particular!', arti: 'Tidak ada yang spesial' },
        { kalimat: "I'll take your word for it", arti: 'Saya pegang kata-kata Anda' },
        { kalimat: 'The same as usual', arti: 'Sama seperti biasanya' },
        { kalimat: 'Almost done!', arti: 'Hampir selesai' },
        { kalimat: "You'll have to step on it", arti: 'Anda harus melaluinya' },
        { kalimat: "I'm in hurry", arti: 'Saya buru-buru' },
        { kalimat: 'Sorry for bothering!', arti: 'Maaf saya mengganggu' },
    ],

    // --- Hari Ke 6 (Index 5) ---
    [
        { kalimat: 'Give me a certain time', arti: 'Berikan waktu yang pasti' },
        { kalimat: 'Provincial !', arti: 'Orang udik' },
        { kalimat: 'Discourages me much!', arti: 'Mematahkan semangat saya' },
        { kalimat: "It's a kind of once-in-life!", arti: 'Sangat jarang terjadi' },
        { kalimat: 'The God Knows!', arti: 'Hanya Tuhan yang tahu!' },
        { kalimat: 'Poor you/me/him/her..', arti: 'Kasihannya Anda/saya/dia...' },
        { kalimat: 'Got a minute?', arti: 'Punya waktu sebentar' },
        { kalimat: "I’ll be shot if I know", arti: 'Saya bisa dibunuh jika saya tahu' },
        { kalimat: 'To argue hot and long', arti: 'Berargumen/Beralasan yang tiada habisnya' },
        { kalimat: 'This one is on me!', arti: 'Biar saya yang selesaikan yang ini' },
        { kalimat: 'No problem', arti: 'Nggak masalah' },
        { kalimat: 'Be Patient', arti: 'Sabar ya' },
        { kalimat: 'Congratulations to you !', arti: 'Saya ucapkan Selamat pada Anda' },
        { kalimat: 'Look at', arti: 'Lihatlah' },
        { kalimat: 'Lucky You', arti: 'Sukses !' },
        { kalimat: 'How beautiful', arti: 'Alangkah indahnya' },
        { kalimat: 'Nice to meet you', arti: 'Senang ketemu kamu' },
        { kalimat: 'How are you?', arti: 'Apa kabar mu?' },
        { kalimat: 'Are you Ok?', arti: 'Apa kamu baik-baik saja?' },
        { kalimat: 'Where are you going?', arti: 'Kemana kamu pergi' },
    ],

    // --- Hari Ke 7 (Index 6) - COMPILATION ---
    [
        // Greeting
        { kalimat: 'Hello / Hallo', arti: 'Helo' },
        { kalimat: 'Hi', arti: 'Hai' },
        { kalimat: 'Good Morning !', arti: 'Selamat pagi !' },
        { kalimat: 'Good day !', arti: 'Selamat Siang !' },
        { kalimat: 'Good Afternoon !', arti: 'Selamat sore !' },
        { kalimat: 'Good evening !', arti: 'Selamat malam !' },
        { kalimat: 'Good night', arti: 'Selamat tidur / malam' },
        { kalimat: 'How are you ?', arti: 'Bagaimana kabarmu ?' },
        { kalimat: 'How do you do ?', arti: 'Apa kabar ? ( Perkenalan )' },
        { kalimat: 'Very well, thank you', arti: 'Baik-baik saja, terima kasih' },
        { kalimat: 'Allow me introduce my self', arti: 'Saya perkenalkan diri saya' },
        { kalimat: 'My name is Boby', arti: 'Nama saya bobi' },
        { kalimat: 'Do you know each other ?', arti: 'Apakah kamu sudah saling kenal ?' },
        { kalimat: 'I am glad to see you', arti: 'Senang bertemu denganmu' },
        { kalimat: 'How long have you been here?', arti: 'Sudah berapa lama anda di sini ?' },
        { kalimat: "I haven't seen you for a long time", arti: 'Sudah lama saya tidak bertemu kamu' },
        { kalimat: 'What a surprise to see you !', arti: 'Benar-benar mengejutkan bertemu denganmu' },
        { kalimat: 'We must keep in touch', arti: 'Kita mesti saling berhubungan' },
        { kalimat: "Don't forget me", arti: 'Jangan lupakan aku' },
        { kalimat: 'What happened ?', arti: 'Apa yang terjadi ?' },
        { kalimat: "What's wrong ?", arti: 'Ada apa ( kamu sakit ) ?' },

        // Congratulations
        { kalimat: 'Congratulations to you !', arti: 'Saya ucapkan selamat pada anda !' },
        { kalimat: 'Congratulations on your escape !', arti: 'Selamat anda terhindari dari bahaya !' },
        { kalimat: 'Please accept my congratulations !', arti: 'Terimalah ucapan selamat saya !' },
        { kalimat: 'Have a good trip !', arti: 'Selamat bepergian !' },
        { kalimat: 'Have a nice sleep !', arti: 'Selamat tidur nyenyak !' },
        { kalimat: 'Have a nice dream !', arti: 'Selamat mimpi indah !' },
        { kalimat: 'Happy new year !', arti: 'Selamat tahun baru !' },
        { kalimat: 'Happy Birthday !', arti: 'Selamat ulang tahun !' },
        { kalimat: 'Good bye ! Bye Bye !', arti: 'Selamat jalan selamat tinggal' },
        { kalimat: 'See you', arti: 'Sampai bertemu' },
        { kalimat: 'See you later', arti: 'Sampai bertemu nanti' },
        { kalimat: 'Good luck', arti: 'Semoga berhasil/semoga sukses' },
        { kalimat: 'Give me love to Rendy', arti: 'Salam hangat saya pada Rendy' },
        { kalimat: 'Give me regards to him', arti: 'Sampaikan salam saya kepadanya' },
        { kalimat: 'I must say good bye', arti: 'Saya ucapkan selamat tinggal' },
        { kalimat: "I hope you'll come again soon", arti: 'Saya harap anda segera datang lagi' },
        { kalimat: 'Come whenever you like', arti: 'Datanglah kapan saja kamu mau' },

        // Excuses
        { kalimat: 'Please pardon me', arti: 'Maafkan saya' },
        { kalimat: 'Excuse me for coming late', arti: 'Maafkan saya datang terlambat' },
        { kalimat: 'May I be excused ?', arti: 'Bisakah saya dimaafkan ?' },
        { kalimat: "It's very regretable", arti: 'Sangat disesalkan hal itu' },
        { kalimat: "I'm so sorry", arti: 'Saya sangat menyesal' },
        { kalimat: "I'm sorry", arti: 'Maaf ( Kalau membuat orang terluka )' },
        { kalimat: 'Forgive me please', arti: 'Maafkan saya' },
        { kalimat: "I didn't mean to hurt you", arti: 'Saya tidak bermaksud menyakitimu' },
        { kalimat: "I'm sorry for not coming to your party", arti: 'Maaf tidak bisa datang ke pestamu' },

        // Thanks
        { kalimat: 'Thanks a lot', arti: 'Terima kasih banyak' },
        { kalimat: 'Thank you very much', arti: 'Terima kasih banyak' },
        { kalimat: 'Thank you so much', arti: 'Terima kasih banyak' },
        { kalimat: 'No, Thanks', arti: 'Tidak, terima kasih' },
        { kalimat: "You're welcome", arti: 'Terima kasih kembali' },
        { kalimat: "Don't mention it", arti: 'Terima kasih kembali' },
        { kalimat: 'I appreciate your helping', arti: 'Saya menghargai pertolonganmu' },
        { kalimat: 'Thanks heaven !', arti: 'Alhamdulillah' },

        // Common Sign
        { kalimat: 'In', arti: 'Masuk' },
        { kalimat: 'Out', arti: 'Keluar' },
        { kalimat: 'Entrance', arti: 'Ada' },
        { kalimat: 'Exit', arti: 'Keluar' },
        { kalimat: 'Push', arti: 'Dorong' },
        { kalimat: 'Way up', arti: 'Jalan naik' },
        { kalimat: 'Pull', arti: 'Tarik' },
        { kalimat: 'Arrival', arti: 'Tiba' },
        { kalimat: 'Departure', arti: 'Berangkat' },
        { kalimat: 'To rent', arti: 'Disewakan' },
        { kalimat: 'To Lift', arti: 'Ke lift' },
        { kalimat: 'Beware !', arti: 'Awas !' },
        { kalimat: 'Admission free', arti: 'Tidak ada pungutan' },
        { kalimat: 'Staff only', arti: 'Hanya untuk anggota staf' },
        { kalimat: 'Fire Extinguisher', arti: 'Alat pemadam kebakaran' },
        { kalimat: 'Emergency exit', arti: 'Pintu darurat' },
        { kalimat: 'To staircase', arti: 'Ke tangga' },
        { kalimat: 'To elevators', arti: 'Ke elevator' },
        { kalimat: 'To escalator', arti: 'Ke tangga berjalan' },
        { kalimat: 'Ground floor', arti: 'Lantai bawah' },
        { kalimat: 'First floor', arti: 'Lantai pertama' },

        // Common Road Sign
        { kalimat: 'No through road', arti: 'Jalan buntu' },
        { kalimat: 'No waiting', arti: 'Dilarang berhenti' },
        { kalimat: 'No stopping for 4 miles', arti: 'Dilarang berhenti sepanjang 4 mil' },
        { kalimat: 'Slow major road a head', arti: 'Pelan-Pelan, jalan raya di depan' },
        { kalimat: 'Halt at major road a head', arti: 'Berhenti di jalan raya di muka' },
        { kalimat: 'End of motorway', arti: 'Akhir jalur lalu lintas cepat' },
        { kalimat: 'No over talking', arti: 'Dilarang mendahului' },
        { kalimat: 'Road works ahead', arti: 'Perbaikan jalan di muka' },
        { kalimat: 'Level Crossing', arti: 'Jalan bercabang' },
        { kalimat: 'To car park', arti: 'Ke tempat parkir' },

        // Requests and Regrets
        { kalimat: 'Let me have it, please', arti: 'Tolonglah berikan kepada saya' },
        { kalimat: 'May i borrow this book', arti: 'Bolehkah saya pinjem buku ini' },
        { kalimat: 'Please, do', arti: 'Tentu, silahkan' },
        { kalimat: 'Can i ask you favour?', arti: 'Bolehkah saya minta tolong?' },
        { kalimat: 'With pleasure, thanks', arti: 'Ya, terima kasih' },
        { kalimat: 'Excuse me, please', arti: 'Maaf...' },
        { kalimat: "It won't happen again", arti: 'Tak kan terjadi lagi' },
        { kalimat: 'Let me try and explain', arti: 'Baiklah saya mencoba menjelaskannya' },
        { kalimat: 'What a pity !', arti: 'Sayang betul' },
        { kalimat: 'How awful', arti: 'Buruk benar' },
        { kalimat: "I'm sorry to hear that", arti: 'Berita itu tidak menyenangkan' },
        { kalimat: "I hope it's nothing serious", arti: 'Mudah-mudahan tidak ada apa-apa' },

        // Questions and Answers (Percakapan)
        { kalimat: 'How do you do ?', arti: 'Apa kabar ?' },
        { kalimat: 'I am good', arti: 'Saya baik saja' },
        { kalimat: 'What is your name ?', arti: 'Siapa nama Anda' },
        { kalimat: 'My name is Jelita', arti: 'Namaku Jelita' },
        { kalimat: 'May I call you Jeli ?', arti: 'Bolehkan saya panggil kamu Jeli aja?' },
        { kalimat: 'With Pleasure', arti: 'Boleh saja, dengan senang hati' },
        { kalimat: 'Where do you live ?', arti: 'Di mana Anda tinggal?' },
        { kalimat: 'I live at Jl A yani no 29', arti: 'Saya tinggal di dalam A Yani no 29' },
        { kalimat: 'Do you have telephone ?', arti: 'Apakah Anda punya telepon ?' },
        { kalimat: "Yes, I have, it's 021-19101974", arti: 'Ya saya punya, ini 021-19101974' },
        { kalimat: 'May I use it ?', arti: 'Bolehkah saya menggunakannya?' },
        { kalimat: 'Certainly, you may', arti: 'Tentu saja boleh' },
        { kalimat: 'Do you live alone ?', arti: 'Kamu tinggal sendirian ?' },
        { kalimat: 'No, I live with my sister', arti: 'Tidak, saya tinggal bersama saudara perempuanku' },
        { kalimat: 'How is your mother ?', arti: 'Bagaimana kabar ibumu ?' },
        { kalimat: 'She is so well', arti: 'Ia baik saja' },
        { kalimat: 'And how old is your sister?', arti: 'Berapa umur saudara perempuanmu ?' },
        { kalimat: 'She is thirty years old', arti: 'Umurnya 30 tahun' },
        { kalimat: 'Is that you, Ayu ?', arti: 'Kaukah itu Ayu ?' },
        { kalimat: 'Yes, I am as you see Jelita', arti: 'Ya, seperti yang kau lihat Jelita' },
        { kalimat: 'Glad to see you too', arti: 'Senang juga bertemu kamu' },
    ],

    [], [], [], [], [], [], [], [], [], [], [], []
])